### ISSUE TITLE
Rules keep logging with wrong log name

### ISSUE THREAD

**Issue by seime** [seaside1/jrule#58] opened 2022-10-09 13:16 UTC
I think this line is troublesome; the JRule instance may contain multiple rules and/or triggers that may execute at the same time. Instead the context (or just logName) must be propagated.

Currently log statements sometimes log with the wrong logName.

https://github.com/seaside1/jrule/blob/2f28a40d723be988f26f619cda3e2c590bcdcc6c/src/main/java/org/openhab/automation/jrule/internal/engine/JRuleEngine.java#L546

**Comment by seaside1** [comment] 2022-10-09 20:42
This is probably related to what I noticed earlier with pr 42, but the bug has probably always been there so not specific to pr 42.

**Comment by querdenker2k** [comment] 2022-10-16 19:31
agree, got the same problem in my test project

**Comment by seaside1** [comment] 2022-10-21 14:04
So my take on the problem is the fact that JRule.java represents one class which can contain multiple
methods with annotations (rules). When executing JRuleContext for multiple methods in the same JRule-class we get this problem. I think this can be resolved by using reflection to get logName or rulename annotation from the calling methods.

Another simple approach would be to synchronize the execution like this:

````java
            JRuleLog.debug(logger, context.getRuleName(), "setting mdc tags: {}", context.getLoggingTags());
                MDC.put(MDC_KEY_RULE, context.getRuleName());
                Arrays.stream(context.getLoggingTags()).forEach(s -> MDC.put(s, s));
                synchronized (rule) {
                    rule.setRuleLogName(context.getLogName());
                    return context.isEventParameterPresent() ? method.invoke(rule, event) : method.invoke(rule);
                }
            } catch (InvocationTargetException e) {
   
``` 

if we synchronize on jrule we won't block multiple rules executing in parallel but we will block in case we try to execute two methods in the same class. This seems to work on my setup, but I haven't tested that long

**Comment by seime** [comment] 2022-10-21 17:16
I have multiple rule methods inside each rule class, so limiting them to execute one at a time would be a no-go for me :)

Could we explore solving this with a ThreadLocal instead?

**Comment by querdenker2k** [comment] 2022-10-21 17:50
ThreadLocal sounds good

**Comment by seaside1** [comment] 2022-10-24 18:19
I'll look into thread local, should work.

**Comment by seaside1** [comment] 2022-11-03 21:29
https://github.com/seaside1/jrule/pull/74

**Comment by seime** [comment] 2022-11-06 11:11
#79 built on top of #74

**Comment by seaside1** [comment] 2022-11-06 15:01
> #79 built on top of #74

Great, I'll try to merge soon, but we should probably get 77 merged first to have that on the way.

**Closed** 2022-11-06 20:14 UTC
